// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tauri command names - Single source of truth
 * TypeScript bindings will be auto-generated from this struct
 */
export type TauriCommands = null;
